### ISSUE TITLE
Use Activity instead of FragmentActivity

### ISSUE THREAD

**Issue by bharathwaaj** [testpress/android-sdk#11]
Testpress Exams SDK api expects `FragmentActivity`. Check if this can be replaced with `Activity`. Else provide reason on why it cannot be done.

**Comment by vignesh-s** [comment]
It requires minimum api level **17**.  Because, for `Activity`  we can use [`android.app.Fragment` ](https://developer.android.com/reference/android/app/Fragment.html) only, it was added in api level 11 and that too support [**nested fragments**](https://developer.android.com/reference/android/app/Fragment.html#getChildFragmentManager()) ( i.e. ExamsListFragment inside CarouselFragment) from api level **17** only. But, our current api level & aim is to support api level **9**.
